### ISSUE TITLE
rename default branch to 'main'

### ISSUE THREAD

**Issue by forresthayes** [p0stalweight/redwood-photo-site#1]
Would you be interested to rename the master branch to main? [GitHub is changing the default name on Oct. 1st](https://github.com/github/renaming#later-this-year) and eventually providing tools to facilitate the transition, but I think we could manage making the change manually at this stage. Its up to you!

Here's one approach, [rename master to main](https://hackernoon.com/how-to-rename-your-git-repositories-from-master-to-main-6i1u3wsu)

**Comment by p0stalweight** [comment]
sure, I'll get around to this soon

**Comment by p0stalweight** [comment]
OK, got around to this.
